### ISSUE TITLE
Automatic GitHub Authentication Issue on Jean-Zay (JZ)

### ISSUE THREAD

**Issue by pvtien96** [jean-zay-users/jean-zay-doc#98]
Hi everyone,

I'm encountering an issue with automatically authenticating GitHub operations (clone, pull, push) from Jean-Zay (JZ). Despite following [the official instructions from GitHub](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh), the authentication process doesn't seem to work as expected.

Here's a summary of the steps I followed:

```bash
ssh-keygen -t ed25519 -C "your_email@example.com"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
```

Then add the SSH key to my GitHub account by following [this instruction](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account).

I also tried: ` ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`

While this process works flawlessly on my local machine, the automatic authentication functions, such as cloning private repositories, still do not function properly on JZ.

Any assistance or insights into resolving this issue would be greatly appreciated.

Thank you!

**Comment by RemiLacroix-IDRIS** [comment]
Hi,

As noted in our FAQ, we recommend using Git over HTTPS instead of SSH: http://www.idris.fr/eng/faqs/git_jean_zay-eng.html. The later would require that you fill a form to register the IP addresses of Github servers, IP addresses that are likely to change.

When using HTTPS, see https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git for managing your credentials.

Best
Rémi

**Comment by pvtien96** [comment]
For those who may need it, [this is the answer](https://jean-zay-doc.readthedocs.io/en/latest/tips/miscellaneous/#clone-git-repo). 
Briefly:

- Use `git clone https://my-institute-gitlab.fr:/my-organisation/my-repo.git` instead of `git clone git@my-institute-gitlab.fr:/my-organisation/my-repo.git`.
- Cache your password: `git config --global credential.helper "cache --timeout=2629800"` (1 month caching).
